kind: Service
apiVersion: v1
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  type: NodePort
  selector:
    app: nginx-tls
  ports:
   - name: nginx-https
     protocol: TCP
     port: 443
     targetPort: 443