apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-gwl
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: prometheus-admin
subjects:
- kind: Group  
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: prometheus-gwl
  apiGroup: rbac.authorization.k8s.io