apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: prometheus-gwl
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: prometheus-admin
  namespace: prometheus
subjects:
- kind: Group  
  name: system:serviceaccounts  
  namespace: prometheus
roleRef:
  kind: Role
  name: prometheus-gwl
  apiGroup: rbac.authorization.k8s.io