---
apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mon
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-mon
  template:
    metadata:
      labels:
        name: nginx-mon
    spec:
      containers:
        - name: nginx
          image: "flashick/nginx-stub:v4"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:0.5.0"
          args:
            - -nginx.scrape-uri=http://127.0.0.1/basic_status
          ports:
            - containerPort: 9113
              protocol: TCP