kind: Service
apiVersion: v1
metadata:
  name: nginx-mon
  namespace: monitoring
  labels:
    name: nginx-mon
spec:
  type: NodePort
  selector:
    name: nginx-mon
  ports:
   - name: nginx-http
     protocol: TCP
     port: 80
     nodePort: 30001
     targetPort: 80
   - name: nginx-exporter
     protocol: TCP
     nodePort: 30003
     port: 9113
     targetPort: 9113