apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hipster-shop-ingress
  labels:
    app: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.tls}}
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
      secretName: hipster-shop-secret
  {{- end }}      
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80